---
title: "Test"
author: "Kyle Deng"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Sys.setenv(CKAN_API_KEY = )
source("get_wage.R")
source("helpers.R")
source("list_wage_occupations.R")
source("salary_range.R")
source("map.R")
```

```{r}
dataset <- get_wage(c(2019, 2020, 2021, 2022))
```

```{r}
list_wage_occupations(dataset, "data")
```

```{r}
salary_range(dataset, "Data scientists", "BC")
```

```{r}
map(dataset, 2023, "Data scientists")
```

```{r}
dataset <- dataset %>%
    mutate(text = paste("Province:", province, "\nMedian wage:", median_wage))

ne_states(country = "Canada", returnclass = "sf") %>%
      rename(province = gn_name) %>%
      select(province, geometry) %>%
      right_join(dataset, by = "province") %>%
      filter(occupation == "Data entry clerks") %>%
      plot_ly(stroke = I("black"), split = ~province, color = ~median_wage, 
              colors = viridis::inferno(99),
              text = ~text, showlegend = FALSE, hoveron = "fills", frame = ~year) %>%
      colorbar(title = "Median wage") %>%
      style(hoverlabel = list(bgcolor = "white")) %>%
      animation_slider(currentvalue = list(prefix="Year: ", font = list(color = "red"))) %>%
      layout(title = list(text = paste("Annual median salary of Data entry clerks across Canada<br>")))
```

```{r}
dataset_2022 <- dataset %>%
  filter(year == "2022-01-01")
```

```{r}
list_wage_occupations(dataset, "data")
entry_clerks <- dataset %>%
  filter(occupation == "Data entry clerks")
```

```{r}
source("NA_outliers.R")
```

```{r}
new_dataset <- process_NA(dataset)
```

```{r}
process_outlier(new_dataset)
```
